### PR TITLE
Add MsBackendMassbankSql backend

### PR DESCRIPTION
**Pull request by jorainer**
Add the `MsBackendMassbankSql` backend that allows to directly access a MassBank SQL database (>= release 2020.10).

### CODE REVIEW

**Review by michaelwitting — COMMENTED** [review]
That simply looks awesome!

**Comment by jorainer** [comment]
Come on - you should at least request some minor changes - that way it's too easy ;)

**Comment by michaelwitting** [comment]
I don't see anything... and your coding style is much better than mine!

**Comment by jorainer** [comment]
Re coding style: mine was terrible, but then I got so many complaints (during package submission to Bioconductor or by Laurent and Sebastian) that I had to adapt :)

**Pull request merged**
